service: blablacar

frameworkVersion: '3'

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  memorySize: 512
  timeout: 10 # 10 sec
  logRetentionInDays: 14
  architecture: arm64
  versionFunctions: false
  stage: dev
  environment:
    SECRET: secret-test-test-test
    TOKEN: token-test-test-test
    TABLE_NAME: ${self:service}-table

functions:
  test:
    handler: index.test
    role: lambdaRole5
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    lambdaRole5:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: lambdaRole5
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: lambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:*'
                    - 'logs:*'
                  Resource: '*'
    lambdaTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: entity
            AttributeType: S
          - AttributeName: id
            AttributeType: S
          - AttributeName: created
            AttributeType: N
          - AttributeName: email
            AttributeType: S
          - AttributeName: to
            AttributeType: S
          - AttributeName: from
            AttributeType: S
          - AttributeName: adminId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: entity
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: CreatedIndex
            KeySchema:
              - AttributeName: entity
                KeyType: HASH
              - AttributeName: created
                KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: UserAndAdminEmailIndex
            KeySchema:
              - AttributeName: entity
                KeyType: HASH
              - AttributeName: email
                KeyType: RANGE
          - IndexName: RideToIndex
            KeySchema:
              - AttributeName: entity
                KeyType: HASH
              - AttributeName: to
                KeyType: RANGE
          - IndexName: RideFromIndex
            KeySchema:
              - AttributeName: entity
                KeyType: HASH
              - AttributeName: from
                KeyType: RANGE
          - IndexName: AdminChatIndex
            KeySchema:
              - AttributeName: entity
                KeyType: HASH
              - AttributeName: adminId
                KeyType: RANGE
        TableName: ${self:service}-table
